apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mysql-credentials"
        objectType: "secretsmanager"
      - objectName: "mongodb-credentials"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: mysql-secrets
    type: Opaque
    data:
    - objectName: mysql-credentials
      key: MYSQL_ROOT_PASSWORD
      property: MYSQL_ROOT_PASSWORD
    - objectName: mysql-credentials
      key: MYSQL_DATABASE
      property: MYSQL_DATABASE
    - objectName: mysql-credentials
      key: MYSQL_USER_READER
      property: MYSQL_USER_READER
    - objectName: mysql-credentials
      key: MYSQL_PASSWORD_READER
      property: MYSQL_PASSWORD_READER
    - objectName: mysql-credentials
      key: MYSQL_USER_WRITER
      property: MYSQL_USER_WRITER
    - objectName: mysql-credentials
      key: MYSQL_PASSWORD_WRITER
      property: MYSQL_PASSWORD_WRITER
  - secretName: mongodb-secrets
    type: Opaque
    data:
    - objectName: mongodb-credentials
      key: MONGO_INITDB_ROOT_USERNAME
      property: MONGO_INITDB_ROOT_USERNAME
    - objectName: mongodb-credentials
      key: MONGO_INITDB_ROOT_PASSWORD
      property: MONGO_INITDB_ROOT_PASSWORD
    - objectName: mongodb-credentials
      key: MONGO_INITDB_DATABASE
      property: MONGO_INITDB_DATABASE
    - objectName: mongodb-credentials
      key: MONGO_USER_WRITER
      property: MONGO_USER_WRITER
    - objectName: mongodb-credentials
      key: MONGO_PASSWORD_WRITER
      property: MONGO_PASSWORD_WRITER