# deployment/k8s/base/secrets/secret-provider.yml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-west-2:746706907394:secret:mysql-credentials-HAytyd"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MYSQL_ROOT_PASSWORD"
            objectAlias: mysql_root_password
          - path: "MYSQL_DATABASE"
            objectAlias: mysql_database
          - path: "MYSQL_USER_READER"
            objectAlias: mysql_user_reader
          - path: "MYSQL_PASSWORD_READER"
            objectAlias: mysql_password_reader
          - path: "MYSQL_USER_WRITER"
            objectAlias: mysql_user_writer
          - path: "MYSQL_PASSWORD_WRITER"
            objectAlias: mysql_password_writer
      - objectName: "arn:aws:secretsmanager:us-west-2:746706907394:secret:mongodb-credentials-NPF0hu"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MONGO_INITDB_ROOT_USERNAME"
            objectAlias: mongo_root_username
          - path: "MONGO_INITDB_ROOT_PASSWORD"
            objectAlias: mongo_root_password
          - path: "MONGO_INITDB_DATABASE"
            objectAlias: mongo_database
          - path: "MONGO_USER_READER"
            objectAlias: mongo_user_reader
          - path: "MONGO_PASSWORD_READER"
            objectAlias: mongo_password_reader
          - path: "MONGO_USER_WRITER"
            objectAlias: mongo_user_writer
          - path: "MONGO_PASSWORD_WRITER"
            objectAlias: mongo_password_writer
  secretObjects:
  - secretName: mysql-secrets
    type: Opaque
    data:
    - objectName: mysql_root_password
      key: MYSQL_ROOT_PASSWORD
    - objectName: mysql_database
      key: MYSQL_DATABASE
    - objectName: mysql_user_reader
      key: MYSQL_USER_READER
    - objectName: mysql_password_reader
      key: MYSQL_PASSWORD_READER
    - objectName: mysql_user_writer
      key: MYSQL_USER_WRITER
    - objectName: mysql_password_writer
      key: MYSQL_PASSWORD_WRITER
  - secretName: mongodb-secrets
    type: Opaque
    data:
    - objectName: mongo_root_username
      key: MONGO_INITDB_ROOT_USERNAME
    - objectName: mongo_root_password
      key: MONGO_INITDB_ROOT_PASSWORD
    - objectName: mongo_database
      key: MONGO_INITDB_DATABASE
    - objectName: mongo_user_reader
      key: MONGO_USER_READER
    - objectName: mongo_password_reader
      key: MONGO_PASSWORD_READER
    - objectName: mongo_user_writer
      key: MONGO_USER_WRITER
    - objectName: mongo_password_writer
      key: MONGO_PASSWORD_WRITER