apiVersion: v1
kind: Service
metadata:
  name: analytical-service
spec:
  type: ClusterIP  # Internal service
  ports:
    - protocol: TCP         
      port: 8080           # Port exposed by the service
      targetPort: 8080     # Port your container is listening on
  selector:
    app: analytical-service