apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: database-secrets-sa  # Add this
      volumes:
      - name: init-scripts
        configMap:
          name: mysql-config
      - name: secrets-store        # Add secrets volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "database-secrets"
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER_READER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER_READER
        - name: MYSQL_PASSWORD_READER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD_READER
        - name: MYSQL_USER_WRITER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER_WRITER
        - name: MYSQL_PASSWORD_WRITER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD_WRITER
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: secrets-store           # Mount secrets
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources:
          requests:
            cpu: "200m"      # 20% of a CPU core
            memory: "256Mi"  # 256MB initial request
          limits:
            cpu: "500m"      # Max 50% of a CPU core
            memory: "512Mi"  # Max 512MB memory
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi