#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
CREATE USER IF NOT EXISTS '$MYSQL_USER_READER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD_READER';
GRANT SELECT ON datadb.* TO '$MYSQL_USER_READER'@'%';

CREATE USER IF NOT EXISTS '$MYSQL_USER_WRITER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD_WRITER';
GRANT SELECT, INSERT, UPDATE, DELETE ON datadb.* TO '$MYSQL_USER_WRITER'@'%';

<<<<<<< HEAD
    FLUSH PRIVILEGES;
=======
FLUSH PRIVILEGES;
>>>>>>> 3cb88e360ffd5ce09dd286ab69091e7b6f84c137
EOSQL