# configmaps/mysql-config.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  01-create-database.sql: |
    CREATE DATABASE IF NOT EXISTS datadb;
    USE datadb;
  02-create-table.sql: |
    USE datadb;

    CREATE TABLE IF NOT EXISTS data (
        id INT AUTO_INCREMENT PRIMARY KEY,
        userid VARCHAR(255) NOT NULL,
        value FLOAT NOT NULL,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  03-create-users.sh: |
    #!/bin/bash
    set -e

    mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
        CREATE USER IF NOT EXISTS '$MYSQL_USER_READER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD_READER';
        GRANT SELECT ON datadb.* TO '$MYSQL_USER_READER'@'%';

        CREATE USER IF NOT EXISTS '$MYSQL_USER_WRITER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD_WRITER';
        GRANT SELECT, INSERT, UPDATE, DELETE ON datadb.* TO '$MYSQL_USER_WRITER'@'%';

        FLUSH PRIVILEGES;
    EOSQL
