apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-result-service
  labels:
    app: show-result-service
    component: frontend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show-result-service
  template:
    metadata:
      labels:
        app: show-result-service
    spec:
      serviceAccountName: database-secrets-sa
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "database-secrets"
      containers:
      - name: show-result-service
        image: mehrdadfordobadi/show-result-service:latest
        env:
          # MongoDB connection (using service discovery)
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USER_READER):$(MONGO_PASSWORD_READER)@mongodb.default.svc.cluster.local:27017/analyticsdb"
        - name: MONGO_USER_READER
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: MONGO_USER_READER
        - name: MONGO_PASSWORD_READER
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: MONGO_PASSWORD_READER
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
          path: /health
          port: 8002
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
          path: /health/ready
          port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
    