apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-result-service
  labels:
    app: show-result-service
    component: frontend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show-result-service
  template:
    metadata:
      labels:
        app: show-result-service
    spec:
      containers:
      - name: show-result-service
        image: mehrdadfordobadi/show-result-service:latest
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
          path: /health
          port: 8002
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
          path: /health/ready
          port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
    