apiVersion: autoscaling/v2
kind : HorizontalPodAutoscaler
metadata:
  name: show-result-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: show-result-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70