# auth-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: backend
    environment: development
spec:
  replicas: 1   # Running two replicas for high availability
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: mehrdadfordobadi/auth-service:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        # Health checks to ensure the service is running properly
        livenessProbe: # Implement health checks to ensure the service is running properly
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        # # Environment variables from ConfigMap and Secrets
        # env:
        # - name: NODE_ENV
        #   value: "production"