apiVersion: v1
kind: Service
metadata:
 name: auth-service
 labels:
   app: auth-service
spec:
 type: ClusterIP
 selector:
   app: auth-service  
 ports:
   - protocol: TCP
     port: 8000
     targetPort: 8000