name: testing the oidc permission

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read  

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS Credentials for China region audience
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::746706907394:role/github-oidc
            aws-region: us-west-2

        - name: List the buckets
          run: aws s3 ls