name: testing secrets

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: create artitfact
              run : 
                echo ${{ secrets.TEXT }} > artifact.txt
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: artifact
                path: artifact.txt